---
- name: install application dependent packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - python-dev
    - python-setuptools
    - python-pip
    - supervisor
  register: deps_installed

- name: install virtualenv
  pip: name=virtualenv state=present

- name: get the flask app
  git: repo={{ project_repository }} dest={{ project_path }}
  when: deps_installed | success

- name: setup virtualenv
  pip: virtualenv={{ project_path }}/venv requirements={{ requirements_file }}

- name: copy gunicorn script for running flask app
  template: src=templates/gunicorn.sh.j2 dest="opt/{{ project_name }}/gunicorn.sh" owner={{ app_user }} group={{ app_group }} mode=755

- name: copy supervisor script
  template: src=templates/supervisor_moonlighty.conf.j2 dest=/etc/supervisor/conf.d/moonlighty.conf

- include: nginx.yml
