---

- name: install nginx
  apt: name=nginx update_cache=yes state=latest
  tags:
    - package

- name: remove nginx default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: copy nginx config
  template: src=nginx_site.conf.j2 dest=/etc/nginx/sites-available/{{ project_name }}.conf

- name: symlink sites-available to sites-enabled
  file: src=/etc/nginx/sites-available/{{ project_name }}.conf dest=/etc/nginx/sites-enabled/{{ project_name }}.conf state=link
  notify: reload nginx

- name: start nginx
  service: name=nginx state=started enabled=yes
  tags:
    - service
