- name: install nginx
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nginx

- name: copy nginx config
  template: src=templates/nginx_site.conf.j2 dest=/etc/nginx/sites-available/moonlighty.conf

- name: symlink sites-available to sites-enabled
  file: src=/etc/nginx/sites-available/moonlighty.conf dest=/etc/nginx/sites-enabled/moonlighty.conf state=link
