---

- name: update the apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - package

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - vim
    - tmux
    - htop
    - atop
    - nethogs
    - lsof
  tags:
    - package
